---
- name: Run dummy ansible task
  hosts: nexus_stage
  become: true
  tasks:
    - name: Print the gateway for each host when defined
      ansible.builtin.debug:
        msg: System {{ inventory_hostname }} has gateway {{ ansible_default_ipv4.gateway }}

